#!/usr/bin/env python3
"""
Regenerate assets-data.js and font-data.js by embedding the files in
assets/ and fonts/ as base64 data URIs.

Run this again whenever you replace a file in assets/ or fonts/ so the
app keeps working with a single double-click (file://) — without it,
the app would need to load those files over the network, which some
browsers block for local files.

Usage:
    python3 build_assets.py
"""
import base64
import json
import mimetypes
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
ASSETS_DIR = os.path.join(ROOT, "assets")
FONTS_DIR = os.path.join(ROOT, "fonts")

IMAGE_FILES = {
    "textbox": "textbox.png",
    "nameBox": "name_box.png",
    "linesBox": "lines_box.png",
    "skip": "skip_button.png",
    "log": "log_button.png",
    "auto": "auto_button.png",
    "next": "next.png",
    "scroll": "scroll.png",
}

VIDEO_FILES = {
    "departureVideo": "departure.mp4",
    "tapVideo": "tap.mp4",
}

FONT_FILE = "GenEiLateMinN_v2.woff2"


def to_data_uri(path, mime):
    with open(path, "rb") as f:
        b64 = base64.b64encode(f.read()).decode("ascii")
    return "data:%s;base64,%s" % (mime, b64)


def main():
    image_data = {}
    for key, filename in IMAGE_FILES.items():
        path = os.path.join(ASSETS_DIR, filename)
        image_data[key] = to_data_uri(path, "image/png")

    for key, filename in VIDEO_FILES.items():
        path = os.path.join(ASSETS_DIR, filename)
        if os.path.exists(path):
            image_data[key] = to_data_uri(path, "video/mp4")
        else:
            print("NOTE: video file not found at", path, "— skipped", key)

    out_assets = os.path.join(ROOT, "assets-data.js")
    with open(out_assets, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_assets.py — do not edit by hand.\n")
        f.write("window.__ASSET_DATA__ = ")
        f.write(json.dumps(image_data, ensure_ascii=False))
        f.write(";\n")
    print("wrote", out_assets)

    font_path = os.path.join(FONTS_DIR, FONT_FILE)
    if os.path.exists(font_path):
        font_uri = to_data_uri(font_path, "font/woff2")
        out_font = os.path.join(ROOT, "font-data.js")
        with open(out_font, "w", encoding="utf-8") as f:
            f.write("// AUTO-GENERATED by build_assets.py — do not edit by hand.\n")
            f.write("window.__FONT_DATA__ = ")
            f.write(json.dumps(font_uri))
            f.write(";\n")
        print("wrote", out_font)
    else:
        print("NOTE: font file not found at", font_path, "— skipped font-data.js")


if __name__ == "__main__":
    main()
